export const AUTH = 'AUTH';
export const LOG_OUT = 'LOG_OUT';
export const GET_USERS = 'GET_USERS'
export const GET_COMPLAINTS = 'GET_COMPLAINTS'
export const GET_COMPLAINTS_BY_USER = 'GET_COMPLAINTS_BY_USER'
export const RESOLVE_COMPLAINT = 'RESOLVE_COMPLAINT'
export const GET_ALL_SUGGESTIONS = 'GET_ALL_SUGGESTIONS'
export const GET_SUGGESTIONS_BY_USER = 'GET_SUGGESTIONS_BY_USER'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_POSTS_BY_USER = 'GET_POSTS_BY_USER'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'






